port: 8080
debug: false
links:
   dynmap:
      name: Survival Dynmap
      server: survival
      port: 8123
   sg-stats:
      name: Survival Games Stats
      server: survivalgames
      port: 8080